service: ecommerce-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
#  stage: dev
  region: eu-west-2

functions:
  hello:
    handler: ecommerce-api.handler.hello
    events:
      - http: GET /hello

plugins:
  - serverless-offline